### ISSUE TITLE
V 1.4 LaiNESwitch Freezes with SX OS

### ISSUE THREAD

**Issue by romnutz** [Kevoot/LaiNESwitch#3]
V 1.4 LaiNESwitch Freezes switch with SX OS V1.3 & 1.4. Just black screen.
V 1.3 LaiNESwitch worked with SX OS V1.3 & 1.4 but had that random freezing bug.
Very good emulator for the switch. Thanks for your effort.

**Comment by romnutz** [comment]
Sorry I didn't realize you were not supporting SX OS.
I will try it without SX OS.

**Comment by romnutz** [comment]
Tried with cfw. This time crashed the switch with nintendo error code screen.
Im on FW 5.1.0 with 128gb exfat

**Comment by Kevoot** [comment]
Please see issue https://github.com/Kevoot/LaiNESwitch/issues/2 as without any further information this is just a report of the same issue.
