### ISSUE TITLE
Boots to black screen on 5.1.0

### ISSUE THREAD

**Issue by RyabDev** [Kevoot/LaiNESwitch#5]
not sure what all versions work but LaiNES 1.0 worked fine but after updating I get a black screen

**Comment by tonyzzz321** [comment]
The release note for latest version 1.4.0 states that you need to put the "res" folder in the root of your SD card.

"IMPORTANT: place the res folder on the root of your sdcard or it'll crash. Will fix paths in a patch asap"

**Comment by RyabDev** [comment]
Ah sorry missed that in the log
